config/routes.rb
PhiNe::Application.routes.draw do

  
  devise_for :members do
    get "/members/sign_out" => "devise/sessions#destroy", :as => :destroy_member_session
  end

  get "welcome/index"

  resources :members

  resources :questions do
    resources :replies
  end

 root :to => 'welcome#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :nickname, :ismentor, :isadmin
  
  has_many :replies
  has_many :questions
  
  validates :nickname, :presence => true, :length => { :minimum => 3 }
  validates :email, :presence => true
  validates :password, :presence => true, :length => { :minimum => 8 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :message
  has_many :replies, :dependent => :delete_all 
  belongs_to :member
  
  validates :message, :presence => true
  
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :message, :member_id, :question_id
  belongs_to :question
  belongs_to :member
  
  validates :message, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_member!

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    logger.debug @questions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question.member = current_member

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  # GET /replies
  # GET /replies.json
  def index
    @question = Question.find(params[:question_id])
    @replies = @question.replies.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    @question = Question.find(params[:question_id])
    @reply = @question.replies.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.json
  def new
    @question = Question.find(params[:question_id])
    @reply = @question.replies.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @question = Question.find(params[:question_id])
    @reply = @question.replies.find(params[:id])
  end

  # POST /replies
  # POST /replies.json
  def create
    @question = Question.find(params[:question_id])
    @reply = @question.replies.build(params[:reply])
    @reply.member = current_member

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @question, notice: 'Reply was successfully created.' }
        format.json { render json: @question, status: :created, location: @reply }
      else
        format.html { render action: "new" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.json
  def update
    @question = Question.find(params[:question_id])
    @reply = @question.replies.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @question = Question.find(params[:question_id])
    @reply = @question.replies.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to replies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "PhiNe", root_path, :class => 'brand' %>
<div class="nav-collapse collapse">
            <ul class="nav">
              <li><%= link_to "Fragen", questions_path %></li>
            </ul>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhiNe" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
	<div id="footer">
	      <div class="container">
	        <p class="muted credit">&copy;2013 PhiNe.de</p>
	      </div>
	    </div>
  </body>
</html>

app/views/members/_form.html.erb
<!-- <%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :Email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Passwort %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->

<%= simple_form_for @member do |f| %>
  <%= f.input :nickname, label: 'Dein Nicknamen' %>
  <%= f.input :email, label: 'Email-Adresse' %>
  <%= f.input :password, label: 'Passwort' %>
  <%= f.button :submit, 'Account erstellen' %>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Mitglieder</h1>

<table>
  <tr>
    <th>Nickname</th>
    <th>IsMentor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.nickname %></td>
    <td><%= member.ismentor %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>Account erstellen</h1>

<%= render 'form' %>

<%= link_to 'Zurück', members_path %>

app/views/members/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nickname:</b>
  <%= @member.nickname %>
</p>

<p>
  <b>Status:</b>
  <%= @member.status %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/questions/_form.html.erb
<%= simple_form_for @question do |f| %>
  <%= f.input :message, label: 'Deine Frage' %>
  <%= f.button :submit, 'Frage erstellen' %>
<% end %>

app/views/questions/edit.html.erb
<h1>Frage bearbeiten</h1>

<p>
  <b>Frage:</b><br />
  <%= @question.message %>
</p>

<%= render 'form' %>

<%= link_to questions_path, :class => "btn btn-small" do %>
<i class="icon-info-sign"></i> Zurück<% end %>

app/views/questions/index.html.erb
<div class="page-header">
  <h1>Fragen</h1><%= link_to new_question_path, :class => "btn" do %><i class="icon-file"></i> Neue Frage<% end %>
</div>

<br />
<%# if !@question.empty? %>
<% @questions.each do |question| %>
  <div class="question">
    <div class="question-message">
      <p><%= question.message %></p>
    </div>
    <div class="question-information">
      <%= "Frage erstellt von: #{question.member.nickname}" %>
    </div>
    <div class="question-information">
      <span class="badge badge-success"><%= question.replies.count %></span>
    </div>
    
    <div class="question-action">
      <p><%= link_to question_path(question), :class => "btn btn-small" do %>
        <i class="icon-info-sign"></i> Details<% end %>
        
        <%= link_to new_question_reply_path(question), :class => "btn btn-small" do %>
        <i class="icon-info-sign"></i> Antwort<% end %>
        
        <% if current_member == question.member %>
	  <%= link_to edit_question_path(question), :class => "btn btn-small" do %>
	  <i class="icon-edit"></i> Bearbeiten<% end %> 
	  <%= link_to question, :class => "btn btn-small", method: :delete, data: { confirm: 'Bist du sicher?' } do %>
	  <i class="icon-trash"></i> Löschen<% end %>
	<% end %>
      </p>
    </div>
  </div>
<hr>
<% end %>
<%# end %>

app/views/questions/new.html.erb
<h1>Neue Frage</h1>

<%= render 'form' %>

<%= link_to 'Zurück zur Übersicht', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Frage:</b><br />
  <%= @question.message %>
</p>
<div class="question-information">
  <%= "Frage erstellt von: #{@question.member.nickname}" %><br />
</div>
<div class="question-information">
  <span class="badge badge-success"><%= @question.replies.count %></span>
</div>

<p>
<% if current_member == @question.member %>
  <%= link_to edit_question_path(@question), :class => "btn btn-small" do %>
  <i class="icon-edit"></i> Bearbeiten<% end %>
  <%= link_to @question, :class => "btn btn-small", method: :delete, data: { confirm: 'Bist du sicher?' } do %>
  <i class="icon-trash"></i> Löschen<% end %>
<% end %>
</p>

<p>
  <b>Antworten:</b><br />

<% if @question.replies.size != 0 %>
<% @question.replies.each do |reply| %>
  <div class="reply">
    <div class="reply-message">
      <p><%= reply.message %></p>
    </div>
    <div class="question-information">
      <%= "Antwort erstellt von: #{reply.member.nickname}" %>
    </div>
    <div class="reply-action">
      <p>      
        <% if current_member == reply.member %>
	  <%= link_to edit_question_reply_path(@question), :class => "btn btn-small" do %>
	  <i class="icon-edit"></i> Bearbeiten<% end %>
	  
	  <%= link_to @question, :class => "btn btn-small", method: :delete, data: { confirm: 'Bist du sicher?' } do %>	  <i class="icon-trash"></i> Löschen<% end %>
	<% end %>
      </p>
    </div>
  </div>
<hr>
<% end %>

<% else %>

<p>
  Noch sind keine Antworten vorhanden.<br />
</p>

<% end %>
</p>

<%= link_to new_question_reply_path(@question), :class => "btn btn-small" do %>
<i class="icon-info-sign"></i> Antwort<% end %>
<%= link_to questions_path, :class => "btn btn-small" do %>
<i class="icon-info-sign"></i> Zurück<% end %>

app/views/replies/_form.html.erb
<%= simple_form_for [@question, @reply] do |f| %>
  <%= f.input :message, label: 'Deine Antwort' %>
  <%= f.button :submit, 'Antwort erstellen' %>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <tr>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @replies.each do |reply| %>
  <tr>
    <td><%= reply.message %></td>
    <td><%= link_to 'Show', reply %></td>
    <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
    <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>Neue Antwort</h1>

<p>
  <b>Frage:</b><br />
  <%= @question.message %>
</p>

<%= render 'form' %>

<%= link_to questions_path, :class => "btn btn-small" do %>
<i class="icon-info-sign"></i> Zurück<% end %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @reply.message %>
</p>


<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>

app/views/welcome/index.html.erb
<!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Wer nicht fragt, bleibt dumm!</h1>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
        <p><a href="#" class="btn btn-primary btn-large">Jetzt Frage stellen &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>